-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [der_bigint_extract]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace der_bigint_extract

/-- [core::ops::bit::{impl core::ops::bit::BitAnd<u8, u8> for &'_0 u8}::bitand]:
    Source: '/rustc/library/core/src/internal_macros.rs', lines 27:12-27:67
    Name pattern: [core::ops::bit::{core::ops::bit::BitAnd<&'0 u8, u8, u8>}::bitand]
    Visibility: public -/
@[rust_fun "core::ops::bit::{core::ops::bit::BitAnd<&'0 u8, u8, u8>}::bitand"]
axiom Shared0U8.Insts.CoreOpsBitBitAndU8U8.bitand
  : Std.U8 → Std.U8 → Result Std.U8

/-- [core::option::{core::option::Option<T>}::is_some_and]:
    Source: '/rustc/library/core/src/option.rs', lines 658:4-658:96
    Name pattern: [core::option::{core::option::Option<@T>}::is_some_and]
    Visibility: public -/
@[rust_fun "core::option::{core::option::Option<@T>}::is_some_and"]
axiom core.option.Option.is_some_and
  {T : Type} {T1 : Type} (opsfunctionFnOnceT1TupleTBoolInst :
  core.ops.function.FnOnce T1 T Bool) :
  Option T → T1 → Result Bool

/-- [core::slice::{[T]}::first]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 155:4-155:43
    Name pattern: [core::slice::{[@T]}::first]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::first"]
axiom core.slice.Slice.first {T : Type} : Slice T → Result (Option T)

/-- [der_bigint_extract::big_integer::TAG]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 31:0-31:23
    Visibility: public -/
@[global_simps, irreducible] def big_integer.TAG : Std.U32 := 2#u32

/-- [der_bigint_extract::big_integer::BigIntError]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 35:0-40:1
    Visibility: public -/
@[discriminant isize]
inductive big_integer.BigIntError where
| Empty : big_integer.BigIntError
| NonMinimal : big_integer.BigIntError

/-- [der_bigint_extract::big_integer::{impl core::fmt::Debug for der_bigint_extract::big_integer::BigIntError}::fmt]:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:9-34:14
    Visibility: public -/
def big_integer.BigIntError.Insts.CoreFmtDebug.fmt
  (self : big_integer.BigIntError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | big_integer.BigIntError.Empty =>
    core.fmt.Formatter.write_str f (toStr "Empty")
  | big_integer.BigIntError.NonMinimal =>
    core.fmt.Formatter.write_str f (toStr "NonMinimal")

/-- Trait implementation: [der_bigint_extract::big_integer::{impl core::fmt::Debug for der_bigint_extract::big_integer::BigIntError}]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:9-34:14 -/
@[reducible]
def big_integer.BigIntError.Insts.CoreFmtDebug : core.fmt.Debug
  big_integer.BigIntError := {
  fmt := big_integer.BigIntError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_bigint_extract::big_integer::{impl core::marker::StructuralPartialEq for der_bigint_extract::big_integer::BigIntError}]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:16-34:25 -/
@[reducible]
def big_integer.BigIntError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq big_integer.BigIntError := {
}

/-- [der_bigint_extract::big_integer::{impl core::cmp::PartialEq<der_bigint_extract::big_integer::BigIntError> for der_bigint_extract::big_integer::BigIntError}::eq]:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:16-34:25
    Visibility: public -/
def big_integer.BigIntError.Insts.CoreCmpPartialEqBigIntError.eq
  (self : big_integer.BigIntError) (other : big_integer.BigIntError) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [der_bigint_extract::big_integer::{impl core::cmp::PartialEq<der_bigint_extract::big_integer::BigIntError> for der_bigint_extract::big_integer::BigIntError}]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:16-34:25 -/
@[reducible]
def big_integer.BigIntError.Insts.CoreCmpPartialEqBigIntError :
  core.cmp.PartialEq big_integer.BigIntError big_integer.BigIntError := {
  eq := big_integer.BigIntError.Insts.CoreCmpPartialEqBigIntError.eq
}

/-- [der_bigint_extract::big_integer::{impl core::cmp::Eq for der_bigint_extract::big_integer::BigIntError}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:27-34:29
    Visibility: public -/
def big_integer.BigIntError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : big_integer.BigIntError) : Result Unit := do
  ok ()

/-- Trait implementation: [der_bigint_extract::big_integer::{impl core::cmp::Eq for der_bigint_extract::big_integer::BigIntError}]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:27-34:29 -/
@[reducible]
def big_integer.BigIntError.Insts.CoreCmpEq : core.cmp.Eq
  big_integer.BigIntError := {
  partialEqInst := big_integer.BigIntError.Insts.CoreCmpPartialEqBigIntError
  assert_fields_are_eq :=
    big_integer.BigIntError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_bigint_extract::big_integer::{impl core::clone::Clone for der_bigint_extract::big_integer::BigIntError}::clone]:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:31-34:36
    Visibility: public -/
def big_integer.BigIntError.Insts.CoreCloneClone.clone
  (self : big_integer.BigIntError) : Result big_integer.BigIntError := do
  ok self

/-- Trait implementation: [der_bigint_extract::big_integer::{impl core::clone::Clone for der_bigint_extract::big_integer::BigIntError}]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:31-34:36 -/
@[reducible]
def big_integer.BigIntError.Insts.CoreCloneClone : core.clone.Clone
  big_integer.BigIntError := {
  clone := big_integer.BigIntError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_bigint_extract::big_integer::{impl core::marker::Copy for der_bigint_extract::big_integer::BigIntError}]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 34:38-34:42 -/
@[reducible]
def big_integer.BigIntError.Insts.CoreMarkerCopy : core.marker.Copy
  big_integer.BigIntError := {
  cloneInst := big_integer.BigIntError.Insts.CoreCloneClone
}

/-- [der_bigint_extract::big_integer::validate_integer_content]:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 48:0-60:1
    Visibility: public -/
def big_integer.validate_integer_content
  (content : Slice Std.U8) :
  Result (core.result.Result Unit big_integer.BigIntError)
  := do
  let b ← core.slice.Slice.is_empty content
  if b
  then ok (core.result.Result.Err big_integer.BigIntError.Empty)
  else
    let i := Slice.len content
    if i >= 2#usize
    then
      let c0 ← Slice.index_usize content 0#usize
      let c1 ← Slice.index_usize content 1#usize
      if c0 = 0#u8
      then
        let i1 ← lift (c1 &&& 128#u8)
        if i1 = 0#u8
        then ok (core.result.Result.Err big_integer.BigIntError.NonMinimal)
        else
          if c0 = 255#u8
          then
            let i2 ← lift (c1 &&& 128#u8)
            if i2 != 0#u8
            then ok (core.result.Result.Err big_integer.BigIntError.NonMinimal)
            else ok (core.result.Result.Ok ())
          else ok (core.result.Result.Ok ())
      else
        if c0 = 255#u8
        then
          let i1 ← lift (c1 &&& 128#u8)
          if i1 != 0#u8
          then ok (core.result.Result.Err big_integer.BigIntError.NonMinimal)
          else ok (core.result.Result.Ok ())
        else ok (core.result.Result.Ok ())
    else ok (core.result.Result.Ok ())

/-- [der_bigint_extract::big_integer::is_negative::closure]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 66:32-66:49 -/
@[reducible]
def big_integer.is_negative.closure := Unit

/-- [der_bigint_extract::big_integer::is_negative::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for der_bigint_extract::big_integer::is_negative::closure}::call_once]:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 66:32-66:49 -/
def
  big_integer.is_negative.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
  (c : big_integer.is_negative.closure) (tupled_args : Std.U8) :
  Result Bool
  := do
  let i ← Shared0U8.Insts.CoreOpsBitBitAndU8U8.bitand tupled_args 128#u8
  ok (i != 0#u8)

/-- Trait implementation: [der_bigint_extract::big_integer::is_negative::{impl core::ops::function::FnOnce<(&'_ u8,), bool> for der_bigint_extract::big_integer::is_negative::closure}]
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 66:32-66:49 -/
@[reducible]
def
  big_integer.is_negative.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
  : core.ops.function.FnOnce big_integer.is_negative.closure Std.U8 Bool := {
  call_once :=
    big_integer.is_negative.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool.call_once
}

/-- [der_bigint_extract::big_integer::is_negative]:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 65:0-67:1
    Visibility: public -/
def big_integer.is_negative (content : Slice Std.U8) : Result Bool := do
  let o ← core.slice.Slice.first content
  core.option.Option.is_some_and
    big_integer.is_negative.closure.Insts.CoreOpsFunctionFnOnceTupleSharedU8Bool
    o ()

/-- [der_bigint_extract::big_integer::encode_minimal_integer_into]: loop body 0:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 97:4-105:5
    Visibility: public -/
@[rust_loop_body]
def big_integer.encode_minimal_integer_into_loop.body
  (content : Slice Std.U8) (start : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  let i ← start + 1#usize
  let i1 := Slice.len content
  if i < i1
  then
    let i2 ← Slice.index_usize content start
    if i2 = 0#u8
    then
      let i3 ← Slice.index_usize content i
      let i4 ← lift (i3 &&& 128#u8)
      if i4 = 0#u8
      then ok (cont i)
      else
        if i2 = 255#u8
        then
          let i5 ← Slice.index_usize content i
          let i6 ← lift (i5 &&& 128#u8)
          if i6 != 0#u8
          then ok (cont i)
          else ok (done start)
        else ok (done start)
    else
      if i2 = 255#u8
      then
        let i3 ← Slice.index_usize content i
        let i4 ← lift (i3 &&& 128#u8)
        if i4 != 0#u8
        then ok (cont i)
        else ok (done start)
      else ok (done start)
  else ok (done start)

/-- [der_bigint_extract::big_integer::encode_minimal_integer_into]: loop 0:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 97:4-105:5
    Visibility: public -/
@[rust_loop]
def big_integer.encode_minimal_integer_into_loop
  (content : Slice Std.U8) (start : Std.Usize) : Result Std.Usize := do
  loop
    (fun start1 => big_integer.encode_minimal_integer_into_loop.body content
      start1)
    start

/-- [der_bigint_extract::big_integer::encode_minimal_integer_into]:
    Source: 'src/../../../der-verified/src/big_integer.rs', lines 89:0-112:1
    Visibility: public -/
def big_integer.encode_minimal_integer_into
  (content : Slice Std.U8) (out : Slice Std.U8) :
  Result ((Option Std.Usize) × (Slice Std.U8))
  := do
  let b ← core.slice.Slice.is_empty content
  if b
  then ok (none, out)
  else
    let start ← big_integer.encode_minimal_integer_into_loop content 0#usize
    let minimal ←
      core.slice.index.Slice.index
        (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8) content
        { start }
    let i := Slice.len out
    let i1 := Slice.len minimal
    if i < i1
    then ok (none, out)
    else
      let i2 := Slice.len minimal
      let (s, index_mut_back) ←
        core.slice.index.Slice.index_mut
          (core.slice.index.SliceIndexRangeToUsizeSlice Std.U8) out
          { «end» := i2 }
      let s1 ← core.slice.Slice.copy_from_slice core.marker.CopyU8 s minimal
      let i3 := Slice.len minimal
      let out1 := index_mut_back s1
      ok (some i3, out1)

end der_bigint_extract
