-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [der_length_extract]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace der_length_extract

/-- [core::slice::{[T]}::first]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 155:4-155:43
    Name pattern: [core::slice::{[@T]}::first]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::first"]
axiom core.slice.Slice.first {T : Type} : Slice T → Result (Option T)

/-- [der_length_extract::length::LengthError]
    Source: 'src/../../../der-verified/src/length.rs', lines 13:0-26:1
    Visibility: public -/
@[discriminant isize]
inductive length.LengthError where
| Truncated : length.LengthError
| Indefinite : length.LengthError
| Reserved : length.LengthError
| NonMinimal : length.LengthError
| TooLarge : length.LengthError

/-- [der_length_extract::length::{impl core::fmt::Debug for der_length_extract::length::LengthError}::fmt]:
    Source: 'src/../../../der-verified/src/length.rs', lines 12:9-12:14
    Visibility: public -/
def length.LengthError.Insts.CoreFmtDebug.fmt
  (self : length.LengthError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | length.LengthError.Truncated =>
    core.fmt.Formatter.write_str f (toStr "Truncated")
  | length.LengthError.Indefinite =>
    core.fmt.Formatter.write_str f (toStr "Indefinite")
  | length.LengthError.Reserved =>
    core.fmt.Formatter.write_str f (toStr "Reserved")
  | length.LengthError.NonMinimal =>
    core.fmt.Formatter.write_str f (toStr "NonMinimal")
  | length.LengthError.TooLarge =>
    core.fmt.Formatter.write_str f (toStr "TooLarge")

/-- Trait implementation: [der_length_extract::length::{impl core::fmt::Debug for der_length_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:9-12:14 -/
@[reducible]
def length.LengthError.Insts.CoreFmtDebug : core.fmt.Debug length.LengthError
  := {
  fmt := length.LengthError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_length_extract::length::{impl core::marker::StructuralPartialEq for der_length_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:16-12:25 -/
@[reducible]
def length.LengthError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq length.LengthError := {
}

/-- [der_length_extract::length::{impl core::cmp::PartialEq<der_length_extract::length::LengthError> for der_length_extract::length::LengthError}::eq]:
    Source: 'src/../../../der-verified/src/length.rs', lines 12:16-12:25
    Visibility: public -/
def length.LengthError.Insts.CoreCmpPartialEqLengthError.eq
  (self : length.LengthError) (other : length.LengthError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [der_length_extract::length::{impl core::cmp::PartialEq<der_length_extract::length::LengthError> for der_length_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:16-12:25 -/
@[reducible]
def length.LengthError.Insts.CoreCmpPartialEqLengthError : core.cmp.PartialEq
  length.LengthError length.LengthError := {
  eq := length.LengthError.Insts.CoreCmpPartialEqLengthError.eq
}

/-- [der_length_extract::length::{impl core::cmp::Eq for der_length_extract::length::LengthError}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/length.rs', lines 12:27-12:29
    Visibility: public -/
def length.LengthError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : length.LengthError) : Result Unit := do
  ok ()

/-- Trait implementation: [der_length_extract::length::{impl core::cmp::Eq for der_length_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:27-12:29 -/
@[reducible]
def length.LengthError.Insts.CoreCmpEq : core.cmp.Eq length.LengthError := {
  partialEqInst := length.LengthError.Insts.CoreCmpPartialEqLengthError
  assert_fields_are_eq :=
    length.LengthError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_length_extract::length::{impl core::clone::Clone for der_length_extract::length::LengthError}::clone]:
    Source: 'src/../../../der-verified/src/length.rs', lines 12:31-12:36
    Visibility: public -/
def length.LengthError.Insts.CoreCloneClone.clone
  (self : length.LengthError) : Result length.LengthError := do
  ok self

/-- Trait implementation: [der_length_extract::length::{impl core::clone::Clone for der_length_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:31-12:36 -/
@[reducible]
def length.LengthError.Insts.CoreCloneClone : core.clone.Clone
  length.LengthError := {
  clone := length.LengthError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_length_extract::length::{impl core::marker::Copy for der_length_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:38-12:42 -/
@[reducible]
def length.LengthError.Insts.CoreMarkerCopy : core.marker.Copy
  length.LengthError := {
  cloneInst := length.LengthError.Insts.CoreCloneClone
}

/-- [der_length_extract::length::encode_length]: loop body 0:
    Source: 'src/../../../der-verified/src/length.rs', lines 43:4-45:5
    Visibility: public -/
@[rust_loop_body]
def length.encode_length_loop0.body
  (be : Array Std.U8 4#usize) (lead : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if lead < 4#usize
  then
    let i ← Array.index_usize be lead
    if i = 0#u8
    then let lead1 ← lead + 1#usize
         ok (cont lead1)
    else ok (done lead)
  else ok (done lead)

/-- [der_length_extract::length::encode_length]: loop 0:
    Source: 'src/../../../der-verified/src/length.rs', lines 43:4-45:5
    Visibility: public -/
@[rust_loop]
def length.encode_length_loop0
  (be : Array Std.U8 4#usize) (lead : Std.Usize) : Result Std.Usize := do
  loop
    (fun lead1 => length.encode_length_loop0.body be lead1)
    lead

/-- [der_length_extract::length::encode_length]: loop body 1:
    Source: 'src/../../../der-verified/src/length.rs', lines 49:4-52:5
    Visibility: public -/
@[rust_loop_body]
def length.encode_length_loop1.body
  (be : Array Std.U8 4#usize) (lead : Std.Usize) (n : Std.Usize)
  (out : Array Std.U8 5#usize) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 5#usize) × Std.Usize) (Array Std.U8
    5#usize))
  := do
  if i < n
  then
    let i1 ← lead + i
    let i2 ← Array.index_usize be i1
    let i3 ← 1#usize + i
    let a ← Array.update out i3 i2
    let i4 ← i + 1#usize
    ok (cont (a, i4))
  else ok (done out)

/-- [der_length_extract::length::encode_length]: loop 1:
    Source: 'src/../../../der-verified/src/length.rs', lines 49:4-52:5
    Visibility: public -/
@[rust_loop]
def length.encode_length_loop1
  (out : Array Std.U8 5#usize) (be : Array Std.U8 4#usize) (lead : Std.Usize)
  (n : Std.Usize) (i : Std.Usize) :
  Result (Array Std.U8 5#usize)
  := do
  loop
    (fun (out1, i1) => length.encode_length_loop1.body be lead n out1 i1)
    (out, i)

/-- [der_length_extract::length::encode_length]:
    Source: 'src/../../../der-verified/src/length.rs', lines 33:0-54:1
    Visibility: public -/
def length.encode_length
  (len : Std.U32) : Result ((Array Std.U8 5#usize) × Std.Usize) := do
  let out := Array.repeat 5#usize 0#u8
  if len < 128#u32
  then
    let i ← lift (UScalar.cast .U8 len)
    let out1 ← Array.update out 0#usize i
    ok (out1, 1#usize)
  else
    let be ← lift (core.num.U32.to_be_bytes len)
    let lead ← length.encode_length_loop0 be 0#usize
    let n ← 4#usize - lead
    let i ← lift (UScalar.cast .U8 n)
    let i1 ← lift (128#u8 ||| i)
    let a ← Array.update out 0#usize i1
    let out1 ← length.encode_length_loop1 a be lead n 0#usize
    let i2 ← 1#usize + n
    ok (out1, i2)

/-- [der_length_extract::length::decode_length]: loop body 0:
    Source: 'src/../../../der-verified/src/length.rs', lines 87:4-90:5
    Visibility: public -/
@[rust_loop_body]
def length.decode_length_loop.body
  (n : Std.Usize) (octets : Slice Std.U8) (val : Std.U32) (i : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  if i < n
  then
    let i1 ← val <<< 8#i32
    let i2 ← Slice.index_usize octets i
    let i3 ← lift (UScalar.cast .U32 i2)
    let val1 ← lift (i1 ||| i3)
    let i4 ← i + 1#usize
    ok (cont (val1, i4))
  else ok (done val)

/-- [der_length_extract::length::decode_length]: loop 0:
    Source: 'src/../../../der-verified/src/length.rs', lines 87:4-90:5
    Visibility: public -/
@[rust_loop]
def length.decode_length_loop
  (n : Std.Usize) (octets : Slice Std.U8) (val : Std.U32) (i : Std.Usize) :
  Result Std.U32
  := do
  loop
    (fun (val1, i1) => length.decode_length_loop.body n octets val1 i1)
    (val, i)

/-- [der_length_extract::length::decode_length]:
    Source: 'src/../../../der-verified/src/length.rs', lines 60:0-95:1
    Visibility: public -/
def length.decode_length
  (input : Slice Std.U8) :
  Result (core.result.Result (Std.U32 × Std.Usize) length.LengthError)
  := do
  let o ← core.slice.Slice.first input
  match o with
  | none => ok (core.result.Result.Err length.LengthError.Truncated)
  | some b =>
    if b < 128#u8
    then
      let i ← lift (UScalar.cast .U32 b)
      ok (core.result.Result.Ok (i, 1#usize))
    else
      if b = 128#u8
      then ok (core.result.Result.Err length.LengthError.Indefinite)
      else
        if b = 255#u8
        then ok (core.result.Result.Err length.LengthError.Reserved)
        else
          let i ← lift (b &&& 127#u8)
          let n ← lift (UScalar.cast .Usize i)
          let i1 := Slice.len input
          let i2 ← 1#usize + n
          if i1 < i2
          then ok (core.result.Result.Err length.LengthError.Truncated)
          else
            let octets ←
              core.slice.index.Slice.index
                (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                { start := 1#usize, «end» := i2 }
            let i3 ← Slice.index_usize octets 0#usize
            if i3 = 0#u8
            then ok (core.result.Result.Err length.LengthError.NonMinimal)
            else
              if n > 4#usize
              then ok (core.result.Result.Err length.LengthError.TooLarge)
              else
                let val ← length.decode_length_loop n octets 0#u32 0#usize
                if val < 128#u32
                then ok (core.result.Result.Err length.LengthError.NonMinimal)
                else
                  let i4 ← 1#usize + n
                  ok (core.result.Result.Ok (val, i4))

end der_length_extract
