-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [der_oid_extract]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace der_oid_extract

/-- [der_oid_extract::oid::TAG]
    Source: 'src/../../../der-verified/src/oid.rs', lines 21:0-21:23
    Visibility: public -/
@[global_simps, irreducible] def oid.TAG : Std.U32 := 6#u32

/-- [der_oid_extract::oid::OidError]
    Source: 'src/../../../der-verified/src/oid.rs', lines 25:0-32:1
    Visibility: public -/
@[discriminant isize]
inductive oid.OidError where
| Empty : oid.OidError
| NonMinimalSubid : oid.OidError
| Truncated : oid.OidError

/-- [der_oid_extract::oid::{impl core::fmt::Debug for der_oid_extract::oid::OidError}::fmt]:
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:9-24:14
    Visibility: public -/
def oid.OidError.Insts.CoreFmtDebug.fmt
  (self : oid.OidError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | oid.OidError.Empty => core.fmt.Formatter.write_str f (toStr "Empty")
  | oid.OidError.NonMinimalSubid =>
    core.fmt.Formatter.write_str f (toStr "NonMinimalSubid")
  | oid.OidError.Truncated =>
    core.fmt.Formatter.write_str f (toStr "Truncated")

/-- Trait implementation: [der_oid_extract::oid::{impl core::fmt::Debug for der_oid_extract::oid::OidError}]
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:9-24:14 -/
@[reducible]
def oid.OidError.Insts.CoreFmtDebug : core.fmt.Debug oid.OidError := {
  fmt := oid.OidError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_oid_extract::oid::{impl core::marker::StructuralPartialEq for der_oid_extract::oid::OidError}]
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:16-24:25 -/
@[reducible]
def oid.OidError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq oid.OidError := {
}

/-- [der_oid_extract::oid::{impl core::cmp::PartialEq<der_oid_extract::oid::OidError> for der_oid_extract::oid::OidError}::eq]:
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:16-24:25
    Visibility: public -/
def oid.OidError.Insts.CoreCmpPartialEqOidError.eq
  (self : oid.OidError) (other : oid.OidError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [der_oid_extract::oid::{impl core::cmp::PartialEq<der_oid_extract::oid::OidError> for der_oid_extract::oid::OidError}]
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:16-24:25 -/
@[reducible]
def oid.OidError.Insts.CoreCmpPartialEqOidError : core.cmp.PartialEq
  oid.OidError oid.OidError := {
  eq := oid.OidError.Insts.CoreCmpPartialEqOidError.eq
}

/-- [der_oid_extract::oid::{impl core::cmp::Eq for der_oid_extract::oid::OidError}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:27-24:29
    Visibility: public -/
def oid.OidError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : oid.OidError) : Result Unit := do
  ok ()

/-- Trait implementation: [der_oid_extract::oid::{impl core::cmp::Eq for der_oid_extract::oid::OidError}]
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:27-24:29 -/
@[reducible]
def oid.OidError.Insts.CoreCmpEq : core.cmp.Eq oid.OidError := {
  partialEqInst := oid.OidError.Insts.CoreCmpPartialEqOidError
  assert_fields_are_eq := oid.OidError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_oid_extract::oid::{impl core::clone::Clone for der_oid_extract::oid::OidError}::clone]:
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:31-24:36
    Visibility: public -/
def oid.OidError.Insts.CoreCloneClone.clone
  (self : oid.OidError) : Result oid.OidError := do
  ok self

/-- Trait implementation: [der_oid_extract::oid::{impl core::clone::Clone for der_oid_extract::oid::OidError}]
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:31-24:36 -/
@[reducible]
def oid.OidError.Insts.CoreCloneClone : core.clone.Clone oid.OidError := {
  clone := oid.OidError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_oid_extract::oid::{impl core::marker::Copy for der_oid_extract::oid::OidError}]
    Source: 'src/../../../der-verified/src/oid.rs', lines 24:38-24:42 -/
@[reducible]
def oid.OidError.Insts.CoreMarkerCopy : core.marker.Copy oid.OidError := {
  cloneInst := oid.OidError.Insts.CoreCloneClone
}

/-- [der_oid_extract::oid::validate_oid]: loop body 0:
    Source: 'src/../../../der-verified/src/oid.rs', lines 49:4-65:1
    Visibility: public -/
@[rust_loop_body]
def oid.validate_oid_loop.body
  (content : Slice Std.U8) (at_subid_start : Bool) (i : Std.Usize) :
  Result (ControlFlow (Bool × Std.Usize) (core.result.Result Unit
    oid.OidError))
  := do
  let i1 := Slice.len content
  if i < i1
  then
    let b ← Slice.index_usize content i
    if at_subid_start
    then
      if b = 128#u8
      then ok (done (core.result.Result.Err oid.OidError.NonMinimalSubid))
      else
        let i2 ← lift (b &&& 128#u8)
        let i3 ← i + 1#usize
        ok (cont (i2 = 0#u8, i3))
    else
      let i2 ← lift (b &&& 128#u8)
      let i3 ← i + 1#usize
      ok (cont (i2 = 0#u8, i3))
  else
    if at_subid_start
    then ok (done (core.result.Result.Ok ()))
    else ok (done (core.result.Result.Err oid.OidError.Truncated))

/-- [der_oid_extract::oid::validate_oid]: loop 0:
    Source: 'src/../../../der-verified/src/oid.rs', lines 49:4-65:1
    Visibility: public -/
@[rust_loop]
def oid.validate_oid_loop
  (content : Slice Std.U8) (at_subid_start : Bool) (i : Std.Usize) :
  Result (core.result.Result Unit oid.OidError)
  := do
  loop
    (fun (at_subid_start1, i1) => oid.validate_oid_loop.body content
      at_subid_start1 i1)
    (at_subid_start, i)

/-- [der_oid_extract::oid::validate_oid]:
    Source: 'src/../../../der-verified/src/oid.rs', lines 38:0-65:1
    Visibility: public -/
def oid.validate_oid
  (content : Slice Std.U8) :
  Result (core.result.Result Unit oid.OidError)
  := do
  let b ← core.slice.Slice.is_empty content
  if b
  then ok (core.result.Result.Err oid.OidError.Empty)
  else oid.validate_oid_loop content true 0#usize

end der_oid_extract
