-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [der_sequence_extract]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace der_sequence_extract

/-- [core::convert::num::ptr_try_from_impls::{impl core::convert::TryFrom<u32, core::num::error::TryFromIntError> for usize}::try_from]:
    Source: '/rustc/library/core/src/convert/num.rs', lines 258:12-258:68
    Name pattern: [core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<usize, u32, core::num::error::TryFromIntError>}::try_from]
    Visibility: public -/
@[rust_fun
  "core::convert::num::ptr_try_from_impls::{core::convert::TryFrom<usize, u32, core::num::error::TryFromIntError>}::try_from"]
axiom Usize.Insts.CoreConvertTryFromU32TryFromIntError.try_from
  :
  Std.U32 → Result (core.result.Result Std.Usize
    core.num.error.TryFromIntError)

/-- [core::fmt::{impl core::fmt::Debug for [T]}::fmt]:
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 3122:4-3122:50
    Name pattern: [core::fmt::{core::fmt::Debug<[@T]>}::fmt]
    Visibility: public -/
@[rust_fun "core::fmt::{core::fmt::Debug<[@T]>}::fmt"]
axiom Slice.Insts.CoreFmtDebug.fmt
  {T : Type} (DebugInst : core.fmt.Debug T) :
  Slice T → core.fmt.Formatter → Result ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter)

/-- Trait implementation: [core::fmt::{impl core::fmt::Debug for [T]}]
    Source: '/rustc/library/core/src/fmt/mod.rs', lines 3121:0-3121:28
    Name pattern: [core::fmt::Debug<[@T]>] -/
@[reducible, rust_trait_impl "core::fmt::Debug<[@T]>"]
def Slice.Insts.CoreFmtDebug {T : Type} (DebugInst : core.fmt.Debug T) :
  core.fmt.Debug (Slice T) := {
  fmt := Slice.Insts.CoreFmtDebug.fmt DebugInst
}

/-- [core::result::{core::result::Result<T, E>}::map_err]:
    Source: '/rustc/library/core/src/result.rs', lines 962:4-964:53
    Name pattern: [core::result::{core::result::Result<@T, @E>}::map_err]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::map_err"]
axiom core.result.Result.map_err
  {T : Type} {E : Type} {F : Type} {O : Type} (opsfunctionFnOnceOTupleEFInst :
  core.ops.function.FnOnce O E F) :
  core.result.Result T E → O → Result (core.result.Result T F)

/-- Trait implementation: [core::slice::cmp::{impl core::cmp::PartialEq<[U]> for [T]}]
    Source: '/rustc/library/core/src/slice/cmp.rs', lines 14:0-16:28
    Name pattern: [core::cmp::PartialEq<[@T], [@U]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<[@T], [@U]>"]
def Slice.Insts.CoreCmpPartialEqSlice {T : Type} {U : Type} (cmpPartialEqInst :
  core.cmp.PartialEq T U) : core.cmp.PartialEq (Slice T) (Slice U) := {
  eq := core.slice.cmp.PartialEqSlice.eq cmpPartialEqInst
  ne := core.slice.cmp.PartialEqSlice.ne cmpPartialEqInst
}

/-- [core::slice::{[T]}::first]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 155:4-155:43
    Name pattern: [core::slice::{[@T]}::first]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::first"]
axiom core.slice.Slice.first {T : Type} : Slice T → Result (Option T)

/-- [der_sequence_extract::length::LengthError]
    Source: 'src/../../../der-verified/src/length.rs', lines 13:0-26:1
    Visibility: public -/
@[discriminant isize]
inductive length.LengthError where
| Truncated : length.LengthError
| Indefinite : length.LengthError
| Reserved : length.LengthError
| NonMinimal : length.LengthError
| TooLarge : length.LengthError

/-- [der_sequence_extract::length::{impl core::fmt::Debug for der_sequence_extract::length::LengthError}::fmt]:
    Source: 'src/../../../der-verified/src/length.rs', lines 12:9-12:14
    Visibility: public -/
def length.LengthError.Insts.CoreFmtDebug.fmt
  (self : length.LengthError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | length.LengthError.Truncated =>
    core.fmt.Formatter.write_str f (toStr "Truncated")
  | length.LengthError.Indefinite =>
    core.fmt.Formatter.write_str f (toStr "Indefinite")
  | length.LengthError.Reserved =>
    core.fmt.Formatter.write_str f (toStr "Reserved")
  | length.LengthError.NonMinimal =>
    core.fmt.Formatter.write_str f (toStr "NonMinimal")
  | length.LengthError.TooLarge =>
    core.fmt.Formatter.write_str f (toStr "TooLarge")

/-- Trait implementation: [der_sequence_extract::length::{impl core::fmt::Debug for der_sequence_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:9-12:14 -/
@[reducible]
def length.LengthError.Insts.CoreFmtDebug : core.fmt.Debug length.LengthError
  := {
  fmt := length.LengthError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_sequence_extract::length::{impl core::marker::StructuralPartialEq for der_sequence_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:16-12:25 -/
@[reducible]
def length.LengthError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq length.LengthError := {
}

/-- [der_sequence_extract::length::{impl core::cmp::PartialEq<der_sequence_extract::length::LengthError> for der_sequence_extract::length::LengthError}::ne]:
    Source: 'src/../../../der-verified/src/length.rs', lines 12:16-12:25
    Visibility: public -/
axiom length.LengthError.Insts.CoreCmpPartialEqLengthError.ne
  : length.LengthError → length.LengthError → Result Bool

/-- [der_sequence_extract::length::{impl core::cmp::PartialEq<der_sequence_extract::length::LengthError> for der_sequence_extract::length::LengthError}::eq]:
    Source: 'src/../../../der-verified/src/length.rs', lines 12:16-12:25
    Visibility: public -/
def length.LengthError.Insts.CoreCmpPartialEqLengthError.eq
  (self : length.LengthError) (other : length.LengthError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [der_sequence_extract::length::{impl core::cmp::PartialEq<der_sequence_extract::length::LengthError> for der_sequence_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:16-12:25 -/
@[reducible]
def length.LengthError.Insts.CoreCmpPartialEqLengthError : core.cmp.PartialEq
  length.LengthError length.LengthError := {
  eq := length.LengthError.Insts.CoreCmpPartialEqLengthError.eq
  ne := length.LengthError.Insts.CoreCmpPartialEqLengthError.ne
}

/-- [der_sequence_extract::length::{impl core::cmp::Eq for der_sequence_extract::length::LengthError}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/length.rs', lines 12:27-12:29
    Visibility: public -/
def length.LengthError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : length.LengthError) : Result Unit := do
  ok ()

/-- Trait implementation: [der_sequence_extract::length::{impl core::cmp::Eq for der_sequence_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:27-12:29 -/
@[reducible]
def length.LengthError.Insts.CoreCmpEq : core.cmp.Eq length.LengthError := {
  partialEqInst := length.LengthError.Insts.CoreCmpPartialEqLengthError
  assert_fields_are_eq :=
    length.LengthError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_sequence_extract::length::{impl core::clone::Clone for der_sequence_extract::length::LengthError}::clone]:
    Source: 'src/../../../der-verified/src/length.rs', lines 12:31-12:36
    Visibility: public -/
def length.LengthError.Insts.CoreCloneClone.clone
  (self : length.LengthError) : Result length.LengthError := do
  ok self

/-- Trait implementation: [der_sequence_extract::length::{impl core::clone::Clone for der_sequence_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:31-12:36 -/
@[reducible]
def length.LengthError.Insts.CoreCloneClone : core.clone.Clone
  length.LengthError := {
  clone := length.LengthError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_sequence_extract::length::{impl core::marker::Copy for der_sequence_extract::length::LengthError}]
    Source: 'src/../../../der-verified/src/length.rs', lines 12:38-12:42 -/
@[reducible]
def length.LengthError.Insts.CoreMarkerCopy : core.marker.Copy
  length.LengthError := {
  cloneInst := length.LengthError.Insts.CoreCloneClone
}

/-- [der_sequence_extract::length::encode_length]: loop body 0:
    Source: 'src/../../../der-verified/src/length.rs', lines 43:4-45:5
    Visibility: public -/
@[rust_loop_body]
def length.encode_length_loop0.body
  (be : Array Std.U8 4#usize) (lead : Std.Usize) :
  Result (ControlFlow Std.Usize Std.Usize)
  := do
  if lead < 4#usize
  then
    let i ← Array.index_usize be lead
    if i = 0#u8
    then let lead1 ← lead + 1#usize
         ok (cont lead1)
    else ok (done lead)
  else ok (done lead)

/-- [der_sequence_extract::length::encode_length]: loop 0:
    Source: 'src/../../../der-verified/src/length.rs', lines 43:4-45:5
    Visibility: public -/
@[rust_loop]
def length.encode_length_loop0
  (be : Array Std.U8 4#usize) (lead : Std.Usize) : Result Std.Usize := do
  loop
    (fun lead1 => length.encode_length_loop0.body be lead1)
    lead

/-- [der_sequence_extract::length::encode_length]: loop body 1:
    Source: 'src/../../../der-verified/src/length.rs', lines 49:4-52:5
    Visibility: public -/
@[rust_loop_body]
def length.encode_length_loop1.body
  (be : Array Std.U8 4#usize) (lead : Std.Usize) (n : Std.Usize)
  (out : Array Std.U8 5#usize) (i : Std.Usize) :
  Result (ControlFlow ((Array Std.U8 5#usize) × Std.Usize) (Array Std.U8
    5#usize))
  := do
  if i < n
  then
    let i1 ← lead + i
    let i2 ← Array.index_usize be i1
    let i3 ← 1#usize + i
    let a ← Array.update out i3 i2
    let i4 ← i + 1#usize
    ok (cont (a, i4))
  else ok (done out)

/-- [der_sequence_extract::length::encode_length]: loop 1:
    Source: 'src/../../../der-verified/src/length.rs', lines 49:4-52:5
    Visibility: public -/
@[rust_loop]
def length.encode_length_loop1
  (out : Array Std.U8 5#usize) (be : Array Std.U8 4#usize) (lead : Std.Usize)
  (n : Std.Usize) (i : Std.Usize) :
  Result (Array Std.U8 5#usize)
  := do
  loop
    (fun (out1, i1) => length.encode_length_loop1.body be lead n out1 i1)
    (out, i)

/-- [der_sequence_extract::length::encode_length]:
    Source: 'src/../../../der-verified/src/length.rs', lines 33:0-54:1
    Visibility: public -/
def length.encode_length
  (len : Std.U32) : Result ((Array Std.U8 5#usize) × Std.Usize) := do
  let out := Array.repeat 5#usize 0#u8
  if len < 128#u32
  then
    let i ← lift (UScalar.cast .U8 len)
    let out1 ← Array.update out 0#usize i
    ok (out1, 1#usize)
  else
    let be ← lift (core.num.U32.to_be_bytes len)
    let lead ← length.encode_length_loop0 be 0#usize
    let n ← 4#usize - lead
    let i ← lift (UScalar.cast .U8 n)
    let i1 ← lift (128#u8 ||| i)
    let a ← Array.update out 0#usize i1
    let out1 ← length.encode_length_loop1 a be lead n 0#usize
    let i2 ← 1#usize + n
    ok (out1, i2)

/-- [der_sequence_extract::length::decode_length]: loop body 0:
    Source: 'src/../../../der-verified/src/length.rs', lines 87:4-90:5
    Visibility: public -/
@[rust_loop_body]
def length.decode_length_loop.body
  (n : Std.Usize) (octets : Slice Std.U8) (val : Std.U32) (i : Std.Usize) :
  Result (ControlFlow (Std.U32 × Std.Usize) Std.U32)
  := do
  if i < n
  then
    let i1 ← val <<< 8#i32
    let i2 ← Slice.index_usize octets i
    let i3 ← lift (UScalar.cast .U32 i2)
    let val1 ← lift (i1 ||| i3)
    let i4 ← i + 1#usize
    ok (cont (val1, i4))
  else ok (done val)

/-- [der_sequence_extract::length::decode_length]: loop 0:
    Source: 'src/../../../der-verified/src/length.rs', lines 87:4-90:5
    Visibility: public -/
@[rust_loop]
def length.decode_length_loop
  (n : Std.Usize) (octets : Slice Std.U8) (val : Std.U32) (i : Std.Usize) :
  Result Std.U32
  := do
  loop
    (fun (val1, i1) => length.decode_length_loop.body n octets val1 i1)
    (val, i)

/-- [der_sequence_extract::length::decode_length]:
    Source: 'src/../../../der-verified/src/length.rs', lines 60:0-95:1
    Visibility: public -/
def length.decode_length
  (input : Slice Std.U8) :
  Result (core.result.Result (Std.U32 × Std.Usize) length.LengthError)
  := do
  let o ← core.slice.Slice.first input
  match o with
  | none => ok (core.result.Result.Err length.LengthError.Truncated)
  | some b =>
    if b < 128#u8
    then
      let i ← lift (UScalar.cast .U32 b)
      ok (core.result.Result.Ok (i, 1#usize))
    else
      if b = 128#u8
      then ok (core.result.Result.Err length.LengthError.Indefinite)
      else
        if b = 255#u8
        then ok (core.result.Result.Err length.LengthError.Reserved)
        else
          let i ← lift (b &&& 127#u8)
          let n ← lift (UScalar.cast .Usize i)
          let i1 := Slice.len input
          let i2 ← 1#usize + n
          if i1 < i2
          then ok (core.result.Result.Err length.LengthError.Truncated)
          else
            let octets ←
              core.slice.index.Slice.index
                (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                { start := 1#usize, «end» := i2 }
            let i3 ← Slice.index_usize octets 0#usize
            if i3 = 0#u8
            then ok (core.result.Result.Err length.LengthError.NonMinimal)
            else
              if n > 4#usize
              then ok (core.result.Result.Err length.LengthError.TooLarge)
              else
                let val ← length.decode_length_loop n octets 0#u32 0#usize
                if val < 128#u32
                then ok (core.result.Result.Err length.LengthError.NonMinimal)
                else
                  let i4 ← 1#usize + n
                  ok (core.result.Result.Ok (val, i4))

/-- [der_sequence_extract::sequence::TAG]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 40:0-40:24
    Visibility: public -/
@[global_simps, irreducible] def sequence.TAG : Std.U32 := 16#u32

/-- [der_sequence_extract::sequence::SET_TAG]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 44:0-44:28
    Visibility: public -/
@[global_simps, irreducible] def sequence.SET_TAG : Std.U32 := 17#u32

/-- [der_sequence_extract::tag::TagError]
    Source: 'src/../../../der-verified/src/tag.rs', lines 39:0-48:1
    Visibility: public -/
@[discriminant isize]
inductive tag.TagError where
| Truncated : tag.TagError
| NonMinimal : tag.TagError
| TooLarge : tag.TagError

/-- [der_sequence_extract::tlv::TlvError]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 24:0-37:1
    Visibility: public -/
@[discriminant isize]
inductive tlv.TlvError where
| Tag : tag.TagError → tlv.TlvError
| Length : length.LengthError → tlv.TlvError
| Truncated : tlv.TlvError
| LengthTooLarge : tlv.TlvError
| TrailingData : tlv.TlvError

/-- [der_sequence_extract::sequence::SequenceError]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 48:0-62:1
    Visibility: public -/
@[discriminant isize]
inductive sequence.SequenceError where
| Element : tlv.TlvError → sequence.SequenceError
| NotConstructed : sequence.SequenceError
| WrongTag : sequence.SequenceError
| Tlv : tlv.TlvError → sequence.SequenceError
| TrailingData : sequence.SequenceError

/-- [der_sequence_extract::tag::{impl core::fmt::Debug for der_sequence_extract::tag::TagError}::fmt]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:9-38:14
    Visibility: public -/
def tag.TagError.Insts.CoreFmtDebug.fmt
  (self : tag.TagError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | tag.TagError.Truncated =>
    core.fmt.Formatter.write_str f (toStr "Truncated")
  | tag.TagError.NonMinimal =>
    core.fmt.Formatter.write_str f (toStr "NonMinimal")
  | tag.TagError.TooLarge => core.fmt.Formatter.write_str f (toStr "TooLarge")

/-- Trait implementation: [der_sequence_extract::tag::{impl core::fmt::Debug for der_sequence_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:9-38:14 -/
@[reducible]
def tag.TagError.Insts.CoreFmtDebug : core.fmt.Debug tag.TagError := {
  fmt := tag.TagError.Insts.CoreFmtDebug.fmt
}

/-- [der_sequence_extract::tlv::{impl core::fmt::Debug for der_sequence_extract::tlv::TlvError}::fmt]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:9-23:14
    Visibility: public -/
def tlv.TlvError.Insts.CoreFmtDebug.fmt
  (self : tlv.TlvError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | tlv.TlvError.Tag __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared tag.TagError.Insts.CoreFmtDebug) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Tag") __self_01
  | tlv.TlvError.Length __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared length.LengthError.Insts.CoreFmtDebug)
        __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Length") __self_01
  | tlv.TlvError.Truncated =>
    core.fmt.Formatter.write_str f (toStr "Truncated")
  | tlv.TlvError.LengthTooLarge =>
    core.fmt.Formatter.write_str f (toStr "LengthTooLarge")
  | tlv.TlvError.TrailingData =>
    core.fmt.Formatter.write_str f (toStr "TrailingData")

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::fmt::Debug for der_sequence_extract::tlv::TlvError}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:9-23:14 -/
@[reducible]
def tlv.TlvError.Insts.CoreFmtDebug : core.fmt.Debug tlv.TlvError := {
  fmt := tlv.TlvError.Insts.CoreFmtDebug.fmt
}

/-- [der_sequence_extract::sequence::{impl core::fmt::Debug for der_sequence_extract::sequence::SequenceError}::fmt]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:9-47:14
    Visibility: public -/
def sequence.SequenceError.Insts.CoreFmtDebug.fmt
  (self : sequence.SequenceError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | sequence.SequenceError.Element __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared tlv.TlvError.Insts.CoreFmtDebug) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Element") __self_01
  | sequence.SequenceError.NotConstructed =>
    core.fmt.Formatter.write_str f (toStr "NotConstructed")
  | sequence.SequenceError.WrongTag =>
    core.fmt.Formatter.write_str f (toStr "WrongTag")
  | sequence.SequenceError.Tlv __self_0 =>
    let __self_01 :=
      Dyn.mk _ (core.fmt.DebugShared tlv.TlvError.Insts.CoreFmtDebug) __self_0
    core.fmt.Formatter.debug_tuple_field1_finish f (toStr "Tlv") __self_01
  | sequence.SequenceError.TrailingData =>
    core.fmt.Formatter.write_str f (toStr "TrailingData")

/-- Trait implementation: [der_sequence_extract::sequence::{impl core::fmt::Debug for der_sequence_extract::sequence::SequenceError}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:9-47:14 -/
@[reducible]
def sequence.SequenceError.Insts.CoreFmtDebug : core.fmt.Debug
  sequence.SequenceError := {
  fmt := sequence.SequenceError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_sequence_extract::sequence::{impl core::marker::StructuralPartialEq for der_sequence_extract::sequence::SequenceError}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:16-47:25 -/
@[reducible]
def sequence.SequenceError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq sequence.SequenceError := {
}

/-- [der_sequence_extract::sequence::{impl core::cmp::PartialEq<der_sequence_extract::sequence::SequenceError> for der_sequence_extract::sequence::SequenceError}::ne]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:16-47:25
    Visibility: public -/
axiom sequence.SequenceError.Insts.CoreCmpPartialEqSequenceError.ne
  : sequence.SequenceError → sequence.SequenceError → Result Bool

/-- [der_sequence_extract::tlv::{impl core::cmp::PartialEq<der_sequence_extract::tlv::TlvError> for der_sequence_extract::tlv::TlvError}::ne]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:16-23:25
    Visibility: public -/
axiom tlv.TlvError.Insts.CoreCmpPartialEqTlvError.ne
  : tlv.TlvError → tlv.TlvError → Result Bool

/-- [der_sequence_extract::tag::{impl core::cmp::PartialEq<der_sequence_extract::tag::TagError> for der_sequence_extract::tag::TagError}::ne]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:16-38:25
    Visibility: public -/
axiom tag.TagError.Insts.CoreCmpPartialEqTagError.ne
  : tag.TagError → tag.TagError → Result Bool

/-- [der_sequence_extract::tag::{impl core::cmp::PartialEq<der_sequence_extract::tag::TagError> for der_sequence_extract::tag::TagError}::eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:16-38:25
    Visibility: public -/
def tag.TagError.Insts.CoreCmpPartialEqTagError.eq
  (self : tag.TagError) (other : tag.TagError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [der_sequence_extract::tag::{impl core::cmp::PartialEq<der_sequence_extract::tag::TagError> for der_sequence_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:16-38:25 -/
@[reducible]
def tag.TagError.Insts.CoreCmpPartialEqTagError : core.cmp.PartialEq
  tag.TagError tag.TagError := {
  eq := tag.TagError.Insts.CoreCmpPartialEqTagError.eq
  ne := tag.TagError.Insts.CoreCmpPartialEqTagError.ne
}

/-- [der_sequence_extract::tlv::{impl core::cmp::PartialEq<der_sequence_extract::tlv::TlvError> for der_sequence_extract::tlv::TlvError}::eq]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:16-23:25
    Visibility: public -/
def tlv.TlvError.Insts.CoreCmpPartialEqTlvError.eq
  (self : tlv.TlvError) (other : tlv.TlvError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | tlv.TlvError.Tag __self_0 =>
      match other with
      | tlv.TlvError.Tag __arg1_0 =>
        tag.TagError.Insts.CoreCmpPartialEqTagError.eq __self_0 __arg1_0
      | tlv.TlvError.Length _ => ok true
      | tlv.TlvError.Truncated => ok true
      | tlv.TlvError.LengthTooLarge => ok true
      | tlv.TlvError.TrailingData => ok true
    | tlv.TlvError.Length __self_0 =>
      match other with
      | tlv.TlvError.Tag _ => ok true
      | tlv.TlvError.Length __arg1_0 =>
        length.LengthError.Insts.CoreCmpPartialEqLengthError.eq __self_0
          __arg1_0
      | tlv.TlvError.Truncated => ok true
      | tlv.TlvError.LengthTooLarge => ok true
      | tlv.TlvError.TrailingData => ok true
    | tlv.TlvError.Truncated => ok true
    | tlv.TlvError.LengthTooLarge => ok true
    | tlv.TlvError.TrailingData => ok true
  else ok false

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::cmp::PartialEq<der_sequence_extract::tlv::TlvError> for der_sequence_extract::tlv::TlvError}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:16-23:25 -/
@[reducible]
def tlv.TlvError.Insts.CoreCmpPartialEqTlvError : core.cmp.PartialEq
  tlv.TlvError tlv.TlvError := {
  eq := tlv.TlvError.Insts.CoreCmpPartialEqTlvError.eq
  ne := tlv.TlvError.Insts.CoreCmpPartialEqTlvError.ne
}

/-- [der_sequence_extract::sequence::{impl core::cmp::PartialEq<der_sequence_extract::sequence::SequenceError> for der_sequence_extract::sequence::SequenceError}::eq]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:16-47:25
    Visibility: public -/
def sequence.SequenceError.Insts.CoreCmpPartialEqSequenceError.eq
  (self : sequence.SequenceError) (other : sequence.SequenceError) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | sequence.SequenceError.Element __self_0 =>
      match other with
      | sequence.SequenceError.Element __arg1_0 =>
        tlv.TlvError.Insts.CoreCmpPartialEqTlvError.eq __self_0 __arg1_0
      | sequence.SequenceError.NotConstructed => ok true
      | sequence.SequenceError.WrongTag => ok true
      | sequence.SequenceError.Tlv _ => ok true
      | sequence.SequenceError.TrailingData => ok true
    | sequence.SequenceError.NotConstructed => ok true
    | sequence.SequenceError.WrongTag => ok true
    | sequence.SequenceError.Tlv __self_0 =>
      match other with
      | sequence.SequenceError.Element _ => ok true
      | sequence.SequenceError.NotConstructed => ok true
      | sequence.SequenceError.WrongTag => ok true
      | sequence.SequenceError.Tlv __arg1_0 =>
        tlv.TlvError.Insts.CoreCmpPartialEqTlvError.eq __self_0 __arg1_0
      | sequence.SequenceError.TrailingData => ok true
    | sequence.SequenceError.TrailingData => ok true
  else ok false

/-- Trait implementation: [der_sequence_extract::sequence::{impl core::cmp::PartialEq<der_sequence_extract::sequence::SequenceError> for der_sequence_extract::sequence::SequenceError}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:16-47:25 -/
@[reducible]
def sequence.SequenceError.Insts.CoreCmpPartialEqSequenceError :
  core.cmp.PartialEq sequence.SequenceError sequence.SequenceError := {
  eq := sequence.SequenceError.Insts.CoreCmpPartialEqSequenceError.eq
  ne := sequence.SequenceError.Insts.CoreCmpPartialEqSequenceError.ne
}

/-- [der_sequence_extract::sequence::{impl core::cmp::Eq for der_sequence_extract::sequence::SequenceError}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:27-47:29
    Visibility: public -/
def sequence.SequenceError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : sequence.SequenceError) : Result Unit := do
  ok ()

/-- Trait implementation: [der_sequence_extract::sequence::{impl core::cmp::Eq for der_sequence_extract::sequence::SequenceError}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:27-47:29 -/
@[reducible]
def sequence.SequenceError.Insts.CoreCmpEq : core.cmp.Eq sequence.SequenceError
  := {
  partialEqInst := sequence.SequenceError.Insts.CoreCmpPartialEqSequenceError
  assert_fields_are_eq :=
    sequence.SequenceError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_sequence_extract::sequence::{impl core::clone::Clone for der_sequence_extract::sequence::SequenceError}::clone]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:31-47:36
    Visibility: public -/
def sequence.SequenceError.Insts.CoreCloneClone.clone
  (self : sequence.SequenceError) : Result sequence.SequenceError := do
  ok self

/-- Trait implementation: [der_sequence_extract::sequence::{impl core::clone::Clone for der_sequence_extract::sequence::SequenceError}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:31-47:36 -/
@[reducible]
def sequence.SequenceError.Insts.CoreCloneClone : core.clone.Clone
  sequence.SequenceError := {
  clone := sequence.SequenceError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_sequence_extract::sequence::{impl core::marker::Copy for der_sequence_extract::sequence::SequenceError}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 47:38-47:42 -/
@[reducible]
def sequence.SequenceError.Insts.CoreMarkerCopy : core.marker.Copy
  sequence.SequenceError := {
  cloneInst := sequence.SequenceError.Insts.CoreCloneClone
}

/-- [der_sequence_extract::sequence::Elements]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 73:0-76:1
    Visibility: public -/
structure sequence.Elements where
  rest : Slice Std.U8
  done : Bool

/-- [der_sequence_extract::sequence::{impl core::fmt::Debug for der_sequence_extract::sequence::Elements<'a>}::fmt]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 72:9-72:14
    Visibility: public -/
def sequence.Elements.Insts.CoreFmtDebug.fmt
  (self : sequence.Elements) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn :=
    Dyn.mk _ (core.fmt.DebugShared (Slice.Insts.CoreFmtDebug core.fmt.DebugU8))
      self.rest
  let dyn1 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugBool) self.done
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "Elements") (toStr
    "rest") dyn (toStr "done") dyn1

/-- Trait implementation: [der_sequence_extract::sequence::{impl core::fmt::Debug for der_sequence_extract::sequence::Elements<'a>}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 72:9-72:14 -/
@[reducible]
def sequence.Elements.Insts.CoreFmtDebug : core.fmt.Debug sequence.Elements
  := {
  fmt := sequence.Elements.Insts.CoreFmtDebug.fmt
}

/-- [der_sequence_extract::sequence::{impl core::clone::Clone for der_sequence_extract::sequence::Elements<'a>}::clone]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 72:16-72:21
    Visibility: public -/
def sequence.Elements.Insts.CoreCloneClone.clone
  (self : sequence.Elements) : Result sequence.Elements := do
  let s ← core.clone.impls.CloneShared.clone self.rest
  let b ← lift (core.clone.impls.CloneBool.clone self.done)
  ok { rest := s, done := b }

/-- Trait implementation: [der_sequence_extract::sequence::{impl core::clone::Clone for der_sequence_extract::sequence::Elements<'a>}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 72:16-72:21 -/
@[reducible]
def sequence.Elements.Insts.CoreCloneClone : core.clone.Clone sequence.Elements
  := {
  clone := sequence.Elements.Insts.CoreCloneClone.clone
}

/-- [der_sequence_extract::sequence::{der_sequence_extract::sequence::Elements<'a>}::new]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 80:4-82:5
    Visibility: public -/
def sequence.Elements.new
  (content : Slice Std.U8) : Result sequence.Elements := do
  ok { rest := content, done := false }

/-- [der_sequence_extract::tag::Class]
    Source: 'src/../../../der-verified/src/tag.rs', lines 15:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive tag.Class where
| Universal : tag.Class
| Application : tag.Class
| ContextSpecific : tag.Class
| Private : tag.Class

/-- [der_sequence_extract::tag::Tag]
    Source: 'src/../../../der-verified/src/tag.rs', lines 28:0-35:1
    Visibility: public -/
structure tag.Tag where
  «class» : tag.Class
  constructed : Bool
  number : Std.U32

/-- [der_sequence_extract::tlv::Tlv]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 15:0-20:1
    Visibility: public -/
structure tlv.Tlv where
  tag : tag.Tag
  value : Slice Std.U8

/-- [der_sequence_extract::tlv::decode_tlv::closure#1]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 57:68-57:91 -/
@[reducible]
def tlv.decode_tlv.closure_1 := Unit

/-- [der_sequence_extract::tlv::decode_tlv::{impl core::ops::function::FnOnce<(der_sequence_extract::length::LengthError,), der_sequence_extract::tlv::TlvError> for der_sequence_extract::tlv::decode_tlv::closure#1}::call_once]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 57:68-57:91 -/
def
  tlv.decode_tlv.closure_1.Insts.CoreOpsFunctionFnOnceTupleLengthErrorTlvError.call_once
  (c : tlv.decode_tlv.closure_1) (tupled_args : length.LengthError) :
  Result tlv.TlvError
  := do
  ok (tlv.TlvError.Length tupled_args)

/-- Trait implementation: [der_sequence_extract::tlv::decode_tlv::{impl core::ops::function::FnOnce<(der_sequence_extract::length::LengthError,), der_sequence_extract::tlv::TlvError> for der_sequence_extract::tlv::decode_tlv::closure#1}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 57:68-57:91 -/
@[reducible]
def
  tlv.decode_tlv.closure_1.Insts.CoreOpsFunctionFnOnceTupleLengthErrorTlvError
  : core.ops.function.FnOnce tlv.decode_tlv.closure_1 length.LengthError
  tlv.TlvError := {
  call_once :=
    tlv.decode_tlv.closure_1.Insts.CoreOpsFunctionFnOnceTupleLengthErrorTlvError.call_once
}

/-- [der_sequence_extract::tlv::decode_tlv::closure]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 56:50-56:70 -/
@[reducible]
def tlv.decode_tlv.closure := Unit

/-- [der_sequence_extract::tlv::decode_tlv::{impl core::ops::function::FnOnce<(der_sequence_extract::tag::TagError,), der_sequence_extract::tlv::TlvError> for der_sequence_extract::tlv::decode_tlv::closure}::call_once]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 56:50-56:70 -/
def
  tlv.decode_tlv.closure.Insts.CoreOpsFunctionFnOnceTupleTagErrorTlvError.call_once
  (c : tlv.decode_tlv.closure) (tupled_args : tag.TagError) :
  Result tlv.TlvError
  := do
  ok (tlv.TlvError.Tag tupled_args)

/-- Trait implementation: [der_sequence_extract::tlv::decode_tlv::{impl core::ops::function::FnOnce<(der_sequence_extract::tag::TagError,), der_sequence_extract::tlv::TlvError> for der_sequence_extract::tlv::decode_tlv::closure}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 56:50-56:70 -/
@[reducible]
def tlv.decode_tlv.closure.Insts.CoreOpsFunctionFnOnceTupleTagErrorTlvError :
  core.ops.function.FnOnce tlv.decode_tlv.closure tag.TagError tlv.TlvError
  := {
  call_once :=
    tlv.decode_tlv.closure.Insts.CoreOpsFunctionFnOnceTupleTagErrorTlvError.call_once
}

/-- [der_sequence_extract::tag::decode_tag]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 94:0-139:1
    Visibility: public -/
axiom tag.decode_tag
  :
  Slice Std.U8 → Result (core.result.Result (tag.Tag × Std.Usize)
    tag.TagError)

/-- [der_sequence_extract::tlv::decode_tlv]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 48:0-74:1
    Visibility: public -/
def tlv.decode_tlv
  (input : Slice Std.U8) :
  Result (core.result.Result (tlv.Tlv × Std.Usize) tlv.TlvError)
  := do
  let r ← tag.decode_tag input
  let r1 ←
    core.result.Result.map_err
      tlv.decode_tlv.closure.Insts.CoreOpsFunctionFnOnceTupleTagErrorTlvError r
      ()
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r1
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let (tag, t_used) := val
    let s ←
      core.slice.index.Slice.index
        (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8) input
        { start := t_used }
    let r2 ← length.decode_length s
    let r3 ←
      core.result.Result.map_err
        tlv.decode_tlv.closure_1.Insts.CoreOpsFunctionFnOnceTupleLengthErrorTlvError
        r2 ()
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r3
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      let (len_u32, l_used) := val1
      let header ← t_used + l_used
      let r4 ←
        Usize.Insts.CoreConvertTryFromU32TryFromIntError.try_from len_u32
      match r4 with
      | core.result.Result.Ok l =>
        let o ← lift (Usize.checked_add header l)
        match o with
        | none => ok (core.result.Result.Err tlv.TlvError.LengthTooLarge)
        | some e =>
          let i := Slice.len input
          if i < e
          then ok (core.result.Result.Err tlv.TlvError.Truncated)
          else
            let s1 ←
              core.slice.index.Slice.index
                (core.slice.index.SliceIndexRangeUsizeSlice Std.U8) input
                { start := header, «end» := e }
            ok (core.result.Result.Ok ({ tag, value := s1 }, e))
      | core.result.Result.Err _ =>
        ok (core.result.Result.Err tlv.TlvError.LengthTooLarge)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        (tlv.Tlv × Std.Usize) (core.convert.FromSame tlv.TlvError) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      (tlv.Tlv × Std.Usize) (core.convert.FromSame tlv.TlvError) residual

/-- [der_sequence_extract::sequence::{impl core::iter::traits::iterator::Iterator<core::result::Result<der_sequence_extract::tlv::Tlv<'a>, der_sequence_extract::tlv::TlvError>> for der_sequence_extract::sequence::Elements<'a>}::next]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 88:4-104:5
    Visibility: public -/
def
  sequence.Elements.Insts.CoreIterTraitsIteratorIteratorResultTlvTlvError.next
  (self : sequence.Elements) :
  Result ((Option (core.result.Result tlv.Tlv tlv.TlvError)) ×
    sequence.Elements)
  := do
  if self.done
  then ok (none, self)
  else
    let b ← core.slice.Slice.is_empty self.rest
    if b
    then ok (none, self)
    else
      let r ← tlv.decode_tlv self.rest
      match r with
      | core.result.Result.Ok p =>
        let (t, used) := p
        let s ←
          core.slice.index.Slice.index
            (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8) self.rest
            { start := used }
        ok (some (core.result.Result.Ok t), { rest := s, done := false })
      | core.result.Result.Err e =>
        ok (some (core.result.Result.Err e), { self with done := true })

/-- Trait implementation: [der_sequence_extract::sequence::{impl core::iter::traits::iterator::Iterator<core::result::Result<der_sequence_extract::tlv::Tlv<'a>, der_sequence_extract::tlv::TlvError>> for der_sequence_extract::sequence::Elements<'a>}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 85:0-105:1 -/
@[reducible]
def sequence.Elements.Insts.CoreIterTraitsIteratorIteratorResultTlvTlvError :
  core.iter.traits.iterator.Iterator sequence.Elements (core.result.Result
  tlv.Tlv tlv.TlvError) := {
  next :=
    sequence.Elements.Insts.CoreIterTraitsIteratorIteratorResultTlvTlvError.next
  step_by :=
    core.iter.traits.iterator.Iterator.step_by.default (Self := sequence.Elements)
  enumerate :=
    core.iter.traits.iterator.Iterator.enumerate.default (Self := sequence.Elements)
  take :=
    core.iter.traits.iterator.Iterator.take.default (Self := sequence.Elements)
}

/-- [der_sequence_extract::sequence::decode_sequence]: loop body 0:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 119:4-126:1
    Visibility: public -/
@[rust_loop_body]
def sequence.decode_sequence_loop.body
  (count : Std.Usize) (iter : sequence.Elements) :
  Result (ControlFlow (Std.Usize × sequence.Elements) (core.result.Result
    Std.Usize sequence.SequenceError))
  := do
  let (o, iter1) ←
    sequence.Elements.Insts.CoreIterTraitsIteratorIteratorResultTlvTlvError.next
      iter
  match o with
  | none => ok (done (core.result.Result.Ok count))
  | some child =>
    match child with
    | core.result.Result.Ok _ =>
      let count1 ← count + 1#usize
      ok (cont (count1, iter1))
    | core.result.Result.Err e =>
      ok (done (core.result.Result.Err (sequence.SequenceError.Element e)))

/-- [der_sequence_extract::sequence::decode_sequence]: loop 0:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 119:4-126:1
    Visibility: public -/
@[rust_loop]
def sequence.decode_sequence_loop
  (count : Std.Usize) (iter : sequence.Elements) :
  Result (core.result.Result Std.Usize sequence.SequenceError)
  := do
  loop
    (fun (count1, iter1) => sequence.decode_sequence_loop.body count1 iter1)
    (count, iter)

/-- [der_sequence_extract::sequence::decode_sequence]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 117:0-126:1
    Visibility: public -/
def sequence.decode_sequence
  (content : Slice Std.U8) :
  Result (core.result.Result Std.Usize sequence.SequenceError)
  := do
  let e ← sequence.Elements.new content
  sequence.decode_sequence_loop 0#usize e

/-- [der_sequence_extract::tag::{impl core::cmp::PartialEq<der_sequence_extract::tag::Class> for der_sequence_extract::tag::Class}::ne]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:16-14:25
    Visibility: public -/
axiom tag.Class.Insts.CoreCmpPartialEqClass.ne
  : tag.Class → tag.Class → Result Bool

/-- [der_sequence_extract::sequence::decode_sequence_tlv::closure]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 142:48-142:73 -/
@[reducible]
def sequence.decode_sequence_tlv.closure := Unit

/-- [der_sequence_extract::sequence::decode_sequence_tlv::{impl core::ops::function::FnOnce<(der_sequence_extract::tlv::TlvError,), der_sequence_extract::sequence::SequenceError> for der_sequence_extract::sequence::decode_sequence_tlv::closure}::call_once]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 142:48-142:73 -/
def
  sequence.decode_sequence_tlv.closure.Insts.CoreOpsFunctionFnOnceTupleTlvErrorSequenceError.call_once
  (c : sequence.decode_sequence_tlv.closure) (tupled_args : tlv.TlvError) :
  Result sequence.SequenceError
  := do
  ok (sequence.SequenceError.Tlv tupled_args)

/-- Trait implementation: [der_sequence_extract::sequence::decode_sequence_tlv::{impl core::ops::function::FnOnce<(der_sequence_extract::tlv::TlvError,), der_sequence_extract::sequence::SequenceError> for der_sequence_extract::sequence::decode_sequence_tlv::closure}]
    Source: 'src/../../../der-verified/src/sequence.rs', lines 142:48-142:73 -/
@[reducible]
def
  sequence.decode_sequence_tlv.closure.Insts.CoreOpsFunctionFnOnceTupleTlvErrorSequenceError
  : core.ops.function.FnOnce sequence.decode_sequence_tlv.closure tlv.TlvError
  sequence.SequenceError := {
  call_once :=
    sequence.decode_sequence_tlv.closure.Insts.CoreOpsFunctionFnOnceTupleTlvErrorSequenceError.call_once
}

/-- [der_sequence_extract::sequence::decode_sequence_tlv]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 141:0-150:1
    Visibility: public -/
def sequence.decode_sequence_tlv
  (input : Slice Std.U8) :
  Result (core.result.Result ((Slice Std.U8) × Std.Usize)
    sequence.SequenceError)
  := do
  let r ← tlv.decode_tlv input
  let r1 ←
    core.result.Result.map_err
      sequence.decode_sequence_tlv.closure.Insts.CoreOpsFunctionFnOnceTupleTlvErrorSequenceError
      r ()
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r1
  match cf with
  | core.ops.control_flow.ControlFlow.Continue p =>
    let (t, used) := p
    let b ←
      tag.Class.Insts.CoreCmpPartialEqClass.ne t.tag.«class»
        tag.Class.Universal
    if b
    then ok (core.result.Result.Err sequence.SequenceError.WrongTag)
    else
      if t.tag.number != sequence.TAG
      then ok (core.result.Result.Err sequence.SequenceError.WrongTag)
      else
        if t.tag.constructed
        then ok (core.result.Result.Ok (t.value, used))
        else ok (core.result.Result.Err sequence.SequenceError.NotConstructed)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      ((Slice Std.U8) × Std.Usize) (core.convert.FromSame
      sequence.SequenceError) residual

/-- [der_sequence_extract::sequence::decode_sequence_tlv_strict]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 158:0-164:1
    Visibility: public -/
def sequence.decode_sequence_tlv_strict
  (input : Slice Std.U8) :
  Result (core.result.Result (Slice Std.U8) sequence.SequenceError)
  := do
  let r ← sequence.decode_sequence_tlv input
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue p =>
    let (content, used) := p
    let i := Slice.len input
    if used != i
    then ok (core.result.Result.Err sequence.SequenceError.TrailingData)
    else ok (core.result.Result.Ok content)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      (Slice Std.U8) (core.convert.FromSame sequence.SequenceError) residual

/-- [der_sequence_extract::tlv::encode_tlv_into]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 93:0-107:1
    Visibility: public -/
axiom tlv.encode_tlv_into
  :
  tag.Tag → Slice Std.U8 → Slice Std.U8 → Result ((Option Std.Usize) ×
    (Slice Std.U8))

/-- [der_sequence_extract::sequence::encode_sequence_into]:
    Source: 'src/../../../der-verified/src/sequence.rs', lines 173:0-176:1
    Visibility: public -/
def sequence.encode_sequence_into
  (elements_content : Slice Std.U8) (out : Slice Std.U8) :
  Result ((Option Std.Usize) × (Slice Std.U8))
  := do
  tlv.encode_tlv_into
    {
      «class» := tag.Class.Universal,
      constructed := true,
      number := sequence.TAG
    } elements_content out

/-- [der_sequence_extract::tag::{impl core::fmt::Debug for der_sequence_extract::tag::Class}::fmt]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:9-14:14
    Visibility: public -/
def tag.Class.Insts.CoreFmtDebug.fmt
  (self : tag.Class) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | tag.Class.Universal => core.fmt.Formatter.write_str f (toStr "Universal")
  | tag.Class.Application =>
    core.fmt.Formatter.write_str f (toStr "Application")
  | tag.Class.ContextSpecific =>
    core.fmt.Formatter.write_str f (toStr "ContextSpecific")
  | tag.Class.Private => core.fmt.Formatter.write_str f (toStr "Private")

/-- Trait implementation: [der_sequence_extract::tag::{impl core::fmt::Debug for der_sequence_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:9-14:14 -/
@[reducible]
def tag.Class.Insts.CoreFmtDebug : core.fmt.Debug tag.Class := {
  fmt := tag.Class.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_sequence_extract::tag::{impl core::marker::StructuralPartialEq for der_sequence_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:16-14:25 -/
@[reducible]
def tag.Class.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq tag.Class := {
}

/-- [der_sequence_extract::tag::{impl core::cmp::PartialEq<der_sequence_extract::tag::Class> for der_sequence_extract::tag::Class}::eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:16-14:25
    Visibility: public -/
def tag.Class.Insts.CoreCmpPartialEqClass.eq
  (self : tag.Class) (other : tag.Class) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [der_sequence_extract::tag::{impl core::cmp::PartialEq<der_sequence_extract::tag::Class> for der_sequence_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:16-14:25 -/
@[reducible]
def tag.Class.Insts.CoreCmpPartialEqClass : core.cmp.PartialEq tag.Class
  tag.Class := {
  eq := tag.Class.Insts.CoreCmpPartialEqClass.eq
  ne := tag.Class.Insts.CoreCmpPartialEqClass.ne
}

/-- [der_sequence_extract::tag::{impl core::cmp::Eq for der_sequence_extract::tag::Class}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:27-14:29
    Visibility: public -/
def tag.Class.Insts.CoreCmpEq.assert_fields_are_eq
  (self : tag.Class) : Result Unit := do
  ok ()

/-- Trait implementation: [der_sequence_extract::tag::{impl core::cmp::Eq for der_sequence_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:27-14:29 -/
@[reducible]
def tag.Class.Insts.CoreCmpEq : core.cmp.Eq tag.Class := {
  partialEqInst := tag.Class.Insts.CoreCmpPartialEqClass
  assert_fields_are_eq := tag.Class.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_sequence_extract::tag::{impl core::clone::Clone for der_sequence_extract::tag::Class}::clone]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:31-14:36
    Visibility: public -/
def tag.Class.Insts.CoreCloneClone.clone
  (self : tag.Class) : Result tag.Class := do
  ok self

/-- Trait implementation: [der_sequence_extract::tag::{impl core::clone::Clone for der_sequence_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:31-14:36 -/
@[reducible]
def tag.Class.Insts.CoreCloneClone : core.clone.Clone tag.Class := {
  clone := tag.Class.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_sequence_extract::tag::{impl core::marker::Copy for der_sequence_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:38-14:42 -/
@[reducible]
def tag.Class.Insts.CoreMarkerCopy : core.marker.Copy tag.Class := {
  cloneInst := tag.Class.Insts.CoreCloneClone
}

/-- [der_sequence_extract::tag::{impl core::fmt::Debug for der_sequence_extract::tag::Tag}::fmt]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:9-27:14
    Visibility: public -/
def tag.Tag.Insts.CoreFmtDebug.fmt
  (self : tag.Tag) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ tag.Class.Insts.CoreFmtDebug self.«class»
  let dyn1 := Dyn.mk _ core.fmt.DebugBool self.constructed
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.number
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Tag") (toStr "class")
    dyn (toStr "constructed") dyn1 (toStr "number") dyn2

/-- Trait implementation: [der_sequence_extract::tag::{impl core::fmt::Debug for der_sequence_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:9-27:14 -/
@[reducible]
def tag.Tag.Insts.CoreFmtDebug : core.fmt.Debug tag.Tag := {
  fmt := tag.Tag.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_sequence_extract::tag::{impl core::marker::StructuralPartialEq for der_sequence_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:16-27:25 -/
@[reducible]
def tag.Tag.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq tag.Tag := {
}

/-- [der_sequence_extract::tag::{impl core::cmp::PartialEq<der_sequence_extract::tag::Tag> for der_sequence_extract::tag::Tag}::ne]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:16-27:25
    Visibility: public -/
axiom tag.Tag.Insts.CoreCmpPartialEqTag.ne
  : tag.Tag → tag.Tag → Result Bool

/-- [der_sequence_extract::tag::{impl core::cmp::PartialEq<der_sequence_extract::tag::Tag> for der_sequence_extract::tag::Tag}::eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:16-27:25
    Visibility: public -/
def tag.Tag.Insts.CoreCmpPartialEqTag.eq
  (self : tag.Tag) (other : tag.Tag) : Result Bool := do
  if self.constructed = other.constructed
  then
    if self.number = other.number
    then
      tag.Class.Insts.CoreCmpPartialEqClass.eq self.«class» other.«class»
    else ok false
  else ok false

/-- Trait implementation: [der_sequence_extract::tag::{impl core::cmp::PartialEq<der_sequence_extract::tag::Tag> for der_sequence_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:16-27:25 -/
@[reducible]
def tag.Tag.Insts.CoreCmpPartialEqTag : core.cmp.PartialEq tag.Tag tag.Tag := {
  eq := tag.Tag.Insts.CoreCmpPartialEqTag.eq
  ne := tag.Tag.Insts.CoreCmpPartialEqTag.ne
}

/-- [der_sequence_extract::tag::{impl core::cmp::Eq for der_sequence_extract::tag::Tag}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:27-27:29
    Visibility: public -/
def tag.Tag.Insts.CoreCmpEq.assert_fields_are_eq
  (self : tag.Tag) : Result Unit := do
  ok ()

/-- Trait implementation: [der_sequence_extract::tag::{impl core::cmp::Eq for der_sequence_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:27-27:29 -/
@[reducible]
def tag.Tag.Insts.CoreCmpEq : core.cmp.Eq tag.Tag := {
  partialEqInst := tag.Tag.Insts.CoreCmpPartialEqTag
  assert_fields_are_eq := tag.Tag.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_sequence_extract::tag::{impl core::clone::Clone for der_sequence_extract::tag::Tag}::clone]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:31-27:36
    Visibility: public -/
def tag.Tag.Insts.CoreCloneClone.clone (self : tag.Tag) : Result tag.Tag := do
  ok self

/-- Trait implementation: [der_sequence_extract::tag::{impl core::clone::Clone for der_sequence_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:31-27:36 -/
@[reducible]
def tag.Tag.Insts.CoreCloneClone : core.clone.Clone tag.Tag := {
  clone := tag.Tag.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_sequence_extract::tag::{impl core::marker::Copy for der_sequence_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:38-27:42 -/
@[reducible]
def tag.Tag.Insts.CoreMarkerCopy : core.marker.Copy tag.Tag := {
  cloneInst := tag.Tag.Insts.CoreCloneClone
}

/-- Trait implementation: [der_sequence_extract::tag::{impl core::marker::StructuralPartialEq for der_sequence_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:16-38:25 -/
@[reducible]
def tag.TagError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq tag.TagError := {
}

/-- [der_sequence_extract::tag::{impl core::cmp::Eq for der_sequence_extract::tag::TagError}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:27-38:29
    Visibility: public -/
def tag.TagError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : tag.TagError) : Result Unit := do
  ok ()

/-- Trait implementation: [der_sequence_extract::tag::{impl core::cmp::Eq for der_sequence_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:27-38:29 -/
@[reducible]
def tag.TagError.Insts.CoreCmpEq : core.cmp.Eq tag.TagError := {
  partialEqInst := tag.TagError.Insts.CoreCmpPartialEqTagError
  assert_fields_are_eq := tag.TagError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_sequence_extract::tag::{impl core::clone::Clone for der_sequence_extract::tag::TagError}::clone]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:31-38:36
    Visibility: public -/
def tag.TagError.Insts.CoreCloneClone.clone
  (self : tag.TagError) : Result tag.TagError := do
  ok self

/-- Trait implementation: [der_sequence_extract::tag::{impl core::clone::Clone for der_sequence_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:31-38:36 -/
@[reducible]
def tag.TagError.Insts.CoreCloneClone : core.clone.Clone tag.TagError := {
  clone := tag.TagError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_sequence_extract::tag::{impl core::marker::Copy for der_sequence_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:38-38:42 -/
@[reducible]
def tag.TagError.Insts.CoreMarkerCopy : core.marker.Copy tag.TagError := {
  cloneInst := tag.TagError.Insts.CoreCloneClone
}

/-- [der_sequence_extract::tag::class_bits]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 50:0-57:1 -/
def tag.class_bits (c : tag.Class) : Result Std.U8 := do
  match c with
  | tag.Class.Universal => ok 0#u8
  | tag.Class.Application => ok 1#u8
  | tag.Class.ContextSpecific => ok 2#u8
  | tag.Class.Private => ok 3#u8

/-- [der_sequence_extract::tag::encode_tag]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 62:0-88:1
    Visibility: public -/
axiom tag.encode_tag : tag.Tag → Result ((Array Std.U8 6#usize) × Std.Usize)

/-- [der_sequence_extract::tlv::{impl core::fmt::Debug for der_sequence_extract::tlv::Tlv<'a>}::fmt]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:9-14:14
    Visibility: public -/
def tlv.Tlv.Insts.CoreFmtDebug.fmt
  (self : tlv.Tlv) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ tag.Tag.Insts.CoreFmtDebug self.tag
  let dyn1 :=
    Dyn.mk _ (core.fmt.DebugShared (core.fmt.DebugShared
      (Slice.Insts.CoreFmtDebug core.fmt.DebugU8))) self.value
  core.fmt.Formatter.debug_struct_field2_finish f (toStr "Tlv") (toStr "tag")
    dyn (toStr "value") dyn1

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::fmt::Debug for der_sequence_extract::tlv::Tlv<'a>}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:9-14:14 -/
@[reducible]
def tlv.Tlv.Insts.CoreFmtDebug : core.fmt.Debug tlv.Tlv := {
  fmt := tlv.Tlv.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::marker::StructuralPartialEq for der_sequence_extract::tlv::Tlv<'a>}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:16-14:25 -/
@[reducible]
def tlv.Tlv.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq tlv.Tlv := {
}

/-- [der_sequence_extract::tlv::{impl core::cmp::PartialEq<der_sequence_extract::tlv::Tlv<'a>> for der_sequence_extract::tlv::Tlv<'a>}::ne]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:16-14:25
    Visibility: public -/
axiom tlv.Tlv.Insts.CoreCmpPartialEqTlv.ne
  : tlv.Tlv → tlv.Tlv → Result Bool

/-- [der_sequence_extract::tlv::{impl core::cmp::PartialEq<der_sequence_extract::tlv::Tlv<'a>> for der_sequence_extract::tlv::Tlv<'a>}::eq]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:16-14:25
    Visibility: public -/
def tlv.Tlv.Insts.CoreCmpPartialEqTlv.eq
  (self : tlv.Tlv) (other : tlv.Tlv) : Result Bool := do
  let b ← tag.Tag.Insts.CoreCmpPartialEqTag.eq self.tag other.tag
  if b
  then
    core.slice.cmp.PartialEqSlice.eq core.cmp.PartialEqU8 self.value
      other.value
  else ok false

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::cmp::PartialEq<der_sequence_extract::tlv::Tlv<'a>> for der_sequence_extract::tlv::Tlv<'a>}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:16-14:25 -/
@[reducible]
def tlv.Tlv.Insts.CoreCmpPartialEqTlv : core.cmp.PartialEq tlv.Tlv tlv.Tlv := {
  eq := tlv.Tlv.Insts.CoreCmpPartialEqTlv.eq
  ne := tlv.Tlv.Insts.CoreCmpPartialEqTlv.ne
}

/-- [der_sequence_extract::tlv::{impl core::cmp::Eq for der_sequence_extract::tlv::Tlv<'a>}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:27-14:29
    Visibility: public -/
def tlv.Tlv.Insts.CoreCmpEq.assert_fields_are_eq
  (self : tlv.Tlv) : Result Unit := do
  ok ()

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::cmp::Eq for der_sequence_extract::tlv::Tlv<'a>}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:27-14:29 -/
@[reducible]
def tlv.Tlv.Insts.CoreCmpEq : core.cmp.Eq tlv.Tlv := {
  partialEqInst := tlv.Tlv.Insts.CoreCmpPartialEqTlv
  assert_fields_are_eq := tlv.Tlv.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_sequence_extract::tlv::{impl core::clone::Clone for der_sequence_extract::tlv::Tlv<'a>}::clone]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:31-14:36
    Visibility: public -/
def tlv.Tlv.Insts.CoreCloneClone.clone (self : tlv.Tlv) : Result tlv.Tlv := do
  ok self

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::clone::Clone for der_sequence_extract::tlv::Tlv<'a>}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:31-14:36 -/
@[reducible]
def tlv.Tlv.Insts.CoreCloneClone : core.clone.Clone tlv.Tlv := {
  clone := tlv.Tlv.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::marker::Copy for der_sequence_extract::tlv::Tlv<'a>}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 14:38-14:42 -/
@[reducible]
def tlv.Tlv.Insts.CoreMarkerCopy : core.marker.Copy tlv.Tlv := {
  cloneInst := tlv.Tlv.Insts.CoreCloneClone
}

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::marker::StructuralPartialEq for der_sequence_extract::tlv::TlvError}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:16-23:25 -/
@[reducible]
def tlv.TlvError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq tlv.TlvError := {
}

/-- [der_sequence_extract::tlv::{impl core::cmp::Eq for der_sequence_extract::tlv::TlvError}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:27-23:29
    Visibility: public -/
def tlv.TlvError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : tlv.TlvError) : Result Unit := do
  ok ()

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::cmp::Eq for der_sequence_extract::tlv::TlvError}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:27-23:29 -/
@[reducible]
def tlv.TlvError.Insts.CoreCmpEq : core.cmp.Eq tlv.TlvError := {
  partialEqInst := tlv.TlvError.Insts.CoreCmpPartialEqTlvError
  assert_fields_are_eq := tlv.TlvError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_sequence_extract::tlv::{impl core::clone::Clone for der_sequence_extract::tlv::TlvError}::clone]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:31-23:36
    Visibility: public -/
def tlv.TlvError.Insts.CoreCloneClone.clone
  (self : tlv.TlvError) : Result tlv.TlvError := do
  ok self

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::clone::Clone for der_sequence_extract::tlv::TlvError}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:31-23:36 -/
@[reducible]
def tlv.TlvError.Insts.CoreCloneClone : core.clone.Clone tlv.TlvError := {
  clone := tlv.TlvError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_sequence_extract::tlv::{impl core::marker::Copy for der_sequence_extract::tlv::TlvError}]
    Source: 'src/../../../der-verified/src/tlv.rs', lines 23:38-23:42 -/
@[reducible]
def tlv.TlvError.Insts.CoreMarkerCopy : core.marker.Copy tlv.TlvError := {
  cloneInst := tlv.TlvError.Insts.CoreCloneClone
}

/-- [der_sequence_extract::tlv::decode_tlv_strict]:
    Source: 'src/../../../der-verified/src/tlv.rs', lines 81:0-87:1
    Visibility: public -/
def tlv.decode_tlv_strict
  (input : Slice Std.U8) :
  Result (core.result.Result tlv.Tlv tlv.TlvError)
  := do
  let r ← tlv.decode_tlv input
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue p =>
    let (t, used) := p
    let i := Slice.len input
    if used != i
    then ok (core.result.Result.Err tlv.TlvError.TrailingData)
    else ok (core.result.Result.Ok t)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      tlv.Tlv (core.convert.FromSame tlv.TlvError) residual

end der_sequence_extract
