-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [der_tag_extract]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace der_tag_extract

/-- [core::slice::{[T]}::first]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 155:4-155:43
    Name pattern: [core::slice::{[@T]}::first]
    Visibility: public -/
@[rust_fun "core::slice::{[@T]}::first"]
axiom core.slice.Slice.first {T : Type} : Slice T → Result (Option T)

/-- [der_tag_extract::tag::Class]
    Source: 'src/../../../der-verified/src/tag.rs', lines 15:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive tag.Class where
| Universal : tag.Class
| Application : tag.Class
| ContextSpecific : tag.Class
| Private : tag.Class

/-- [der_tag_extract::tag::{impl core::fmt::Debug for der_tag_extract::tag::Class}::fmt]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:9-14:14
    Visibility: public -/
def tag.Class.Insts.CoreFmtDebug.fmt
  (self : tag.Class) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | tag.Class.Universal => core.fmt.Formatter.write_str f (toStr "Universal")
  | tag.Class.Application =>
    core.fmt.Formatter.write_str f (toStr "Application")
  | tag.Class.ContextSpecific =>
    core.fmt.Formatter.write_str f (toStr "ContextSpecific")
  | tag.Class.Private => core.fmt.Formatter.write_str f (toStr "Private")

/-- Trait implementation: [der_tag_extract::tag::{impl core::fmt::Debug for der_tag_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:9-14:14 -/
@[reducible]
def tag.Class.Insts.CoreFmtDebug : core.fmt.Debug tag.Class := {
  fmt := tag.Class.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_tag_extract::tag::{impl core::marker::StructuralPartialEq for der_tag_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:16-14:25 -/
@[reducible]
def tag.Class.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq tag.Class := {
}

/-- [der_tag_extract::tag::{impl core::cmp::PartialEq<der_tag_extract::tag::Class> for der_tag_extract::tag::Class}::eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:16-14:25
    Visibility: public -/
def tag.Class.Insts.CoreCmpPartialEqClass.eq
  (self : tag.Class) (other : tag.Class) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [der_tag_extract::tag::{impl core::cmp::PartialEq<der_tag_extract::tag::Class> for der_tag_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:16-14:25 -/
@[reducible]
def tag.Class.Insts.CoreCmpPartialEqClass : core.cmp.PartialEq tag.Class
  tag.Class := {
  eq := tag.Class.Insts.CoreCmpPartialEqClass.eq
}

/-- [der_tag_extract::tag::{impl core::cmp::Eq for der_tag_extract::tag::Class}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:27-14:29
    Visibility: public -/
def tag.Class.Insts.CoreCmpEq.assert_fields_are_eq
  (self : tag.Class) : Result Unit := do
  ok ()

/-- Trait implementation: [der_tag_extract::tag::{impl core::cmp::Eq for der_tag_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:27-14:29 -/
@[reducible]
def tag.Class.Insts.CoreCmpEq : core.cmp.Eq tag.Class := {
  partialEqInst := tag.Class.Insts.CoreCmpPartialEqClass
  assert_fields_are_eq := tag.Class.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_tag_extract::tag::{impl core::clone::Clone for der_tag_extract::tag::Class}::clone]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:31-14:36
    Visibility: public -/
def tag.Class.Insts.CoreCloneClone.clone
  (self : tag.Class) : Result tag.Class := do
  ok self

/-- Trait implementation: [der_tag_extract::tag::{impl core::clone::Clone for der_tag_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:31-14:36 -/
@[reducible]
def tag.Class.Insts.CoreCloneClone : core.clone.Clone tag.Class := {
  clone := tag.Class.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_tag_extract::tag::{impl core::marker::Copy for der_tag_extract::tag::Class}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 14:38-14:42 -/
@[reducible]
def tag.Class.Insts.CoreMarkerCopy : core.marker.Copy tag.Class := {
  cloneInst := tag.Class.Insts.CoreCloneClone
}

/-- [der_tag_extract::tag::Tag]
    Source: 'src/../../../der-verified/src/tag.rs', lines 28:0-35:1
    Visibility: public -/
structure tag.Tag where
  «class» : tag.Class
  constructed : Bool
  number : Std.U32

/-- [der_tag_extract::tag::{impl core::fmt::Debug for der_tag_extract::tag::Tag}::fmt]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:9-27:14
    Visibility: public -/
def tag.Tag.Insts.CoreFmtDebug.fmt
  (self : tag.Tag) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ tag.Class.Insts.CoreFmtDebug self.«class»
  let dyn1 := Dyn.mk _ core.fmt.DebugBool self.constructed
  let dyn2 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU32) self.number
  core.fmt.Formatter.debug_struct_field3_finish f (toStr "Tag") (toStr "class")
    dyn (toStr "constructed") dyn1 (toStr "number") dyn2

/-- Trait implementation: [der_tag_extract::tag::{impl core::fmt::Debug for der_tag_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:9-27:14 -/
@[reducible]
def tag.Tag.Insts.CoreFmtDebug : core.fmt.Debug tag.Tag := {
  fmt := tag.Tag.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_tag_extract::tag::{impl core::marker::StructuralPartialEq for der_tag_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:16-27:25 -/
@[reducible]
def tag.Tag.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq tag.Tag := {
}

/-- [der_tag_extract::tag::{impl core::cmp::PartialEq<der_tag_extract::tag::Tag> for der_tag_extract::tag::Tag}::eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:16-27:25
    Visibility: public -/
def tag.Tag.Insts.CoreCmpPartialEqTag.eq
  (self : tag.Tag) (other : tag.Tag) : Result Bool := do
  if self.constructed = other.constructed
  then
    if self.number = other.number
    then
      tag.Class.Insts.CoreCmpPartialEqClass.eq self.«class» other.«class»
    else ok false
  else ok false

/-- Trait implementation: [der_tag_extract::tag::{impl core::cmp::PartialEq<der_tag_extract::tag::Tag> for der_tag_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:16-27:25 -/
@[reducible]
def tag.Tag.Insts.CoreCmpPartialEqTag : core.cmp.PartialEq tag.Tag tag.Tag := {
  eq := tag.Tag.Insts.CoreCmpPartialEqTag.eq
}

/-- [der_tag_extract::tag::{impl core::cmp::Eq for der_tag_extract::tag::Tag}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:27-27:29
    Visibility: public -/
def tag.Tag.Insts.CoreCmpEq.assert_fields_are_eq
  (self : tag.Tag) : Result Unit := do
  ok ()

/-- Trait implementation: [der_tag_extract::tag::{impl core::cmp::Eq for der_tag_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:27-27:29 -/
@[reducible]
def tag.Tag.Insts.CoreCmpEq : core.cmp.Eq tag.Tag := {
  partialEqInst := tag.Tag.Insts.CoreCmpPartialEqTag
  assert_fields_are_eq := tag.Tag.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_tag_extract::tag::{impl core::clone::Clone for der_tag_extract::tag::Tag}::clone]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:31-27:36
    Visibility: public -/
def tag.Tag.Insts.CoreCloneClone.clone (self : tag.Tag) : Result tag.Tag := do
  ok self

/-- Trait implementation: [der_tag_extract::tag::{impl core::clone::Clone for der_tag_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:31-27:36 -/
@[reducible]
def tag.Tag.Insts.CoreCloneClone : core.clone.Clone tag.Tag := {
  clone := tag.Tag.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_tag_extract::tag::{impl core::marker::Copy for der_tag_extract::tag::Tag}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 27:38-27:42 -/
@[reducible]
def tag.Tag.Insts.CoreMarkerCopy : core.marker.Copy tag.Tag := {
  cloneInst := tag.Tag.Insts.CoreCloneClone
}

/-- [der_tag_extract::tag::TagError]
    Source: 'src/../../../der-verified/src/tag.rs', lines 39:0-48:1
    Visibility: public -/
@[discriminant isize]
inductive tag.TagError where
| Truncated : tag.TagError
| NonMinimal : tag.TagError
| TooLarge : tag.TagError

/-- [der_tag_extract::tag::{impl core::fmt::Debug for der_tag_extract::tag::TagError}::fmt]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:9-38:14
    Visibility: public -/
def tag.TagError.Insts.CoreFmtDebug.fmt
  (self : tag.TagError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | tag.TagError.Truncated =>
    core.fmt.Formatter.write_str f (toStr "Truncated")
  | tag.TagError.NonMinimal =>
    core.fmt.Formatter.write_str f (toStr "NonMinimal")
  | tag.TagError.TooLarge => core.fmt.Formatter.write_str f (toStr "TooLarge")

/-- Trait implementation: [der_tag_extract::tag::{impl core::fmt::Debug for der_tag_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:9-38:14 -/
@[reducible]
def tag.TagError.Insts.CoreFmtDebug : core.fmt.Debug tag.TagError := {
  fmt := tag.TagError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [der_tag_extract::tag::{impl core::marker::StructuralPartialEq for der_tag_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:16-38:25 -/
@[reducible]
def tag.TagError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq tag.TagError := {
}

/-- [der_tag_extract::tag::{impl core::cmp::PartialEq<der_tag_extract::tag::TagError> for der_tag_extract::tag::TagError}::eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:16-38:25
    Visibility: public -/
def tag.TagError.Insts.CoreCmpPartialEqTagError.eq
  (self : tag.TagError) (other : tag.TagError) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [der_tag_extract::tag::{impl core::cmp::PartialEq<der_tag_extract::tag::TagError> for der_tag_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:16-38:25 -/
@[reducible]
def tag.TagError.Insts.CoreCmpPartialEqTagError : core.cmp.PartialEq
  tag.TagError tag.TagError := {
  eq := tag.TagError.Insts.CoreCmpPartialEqTagError.eq
}

/-- [der_tag_extract::tag::{impl core::cmp::Eq for der_tag_extract::tag::TagError}::assert_fields_are_eq]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:27-38:29
    Visibility: public -/
def tag.TagError.Insts.CoreCmpEq.assert_fields_are_eq
  (self : tag.TagError) : Result Unit := do
  ok ()

/-- Trait implementation: [der_tag_extract::tag::{impl core::cmp::Eq for der_tag_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:27-38:29 -/
@[reducible]
def tag.TagError.Insts.CoreCmpEq : core.cmp.Eq tag.TagError := {
  partialEqInst := tag.TagError.Insts.CoreCmpPartialEqTagError
  assert_fields_are_eq := tag.TagError.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [der_tag_extract::tag::{impl core::clone::Clone for der_tag_extract::tag::TagError}::clone]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:31-38:36
    Visibility: public -/
def tag.TagError.Insts.CoreCloneClone.clone
  (self : tag.TagError) : Result tag.TagError := do
  ok self

/-- Trait implementation: [der_tag_extract::tag::{impl core::clone::Clone for der_tag_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:31-38:36 -/
@[reducible]
def tag.TagError.Insts.CoreCloneClone : core.clone.Clone tag.TagError := {
  clone := tag.TagError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [der_tag_extract::tag::{impl core::marker::Copy for der_tag_extract::tag::TagError}]
    Source: 'src/../../../der-verified/src/tag.rs', lines 38:38-38:42 -/
@[reducible]
def tag.TagError.Insts.CoreMarkerCopy : core.marker.Copy tag.TagError := {
  cloneInst := tag.TagError.Insts.CoreCloneClone
}

/-- [der_tag_extract::tag::class_bits]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 50:0-57:1 -/
def tag.class_bits (c : tag.Class) : Result Std.U8 := do
  match c with
  | tag.Class.Universal => ok 0#u8
  | tag.Class.Application => ok 1#u8
  | tag.Class.ContextSpecific => ok 2#u8
  | tag.Class.Private => ok 3#u8

/-- [der_tag_extract::tag::encode_tag]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 62:0-88:1
    Visibility: public -/
axiom tag.encode_tag : tag.Tag → Result ((Array Std.U8 6#usize) × Std.Usize)

/-- [der_tag_extract::tag::decode_tag]: loop body 0:
    Source: 'src/../../../der-verified/src/tag.rs', lines 125:48-142:5
    Visibility: public -/
@[rust_loop_body]
def tag.decode_tag_loop.body
  (input : Slice Std.U8) (i : Std.Usize) (number : Std.U32) (count : Std.Usize)
  :
  Result (ControlFlow (Std.Usize × Std.U32 × Std.Usize) (core.result.Result
    (Std.U32 × Std.Usize) tag.TagError))
  := do
  let o ←
    core.slice.Slice.get (core.slice.index.SliceIndexUsizeSlice Std.U8) input i
  match o with
  | none => ok (done (core.result.Result.Err tag.TagError.Truncated))
  | some b =>
    if count = 0#usize
    then
      if b = 128#u8
      then ok (done (core.result.Result.Err tag.TagError.NonMinimal))
      else
        let i1 ← core.num.U32.MAX >>> 7#i32
        if number > i1
        then ok (done (core.result.Result.Err tag.TagError.TooLarge))
        else
          let i2 ← number <<< 7#i32
          let i3 ← lift (b &&& 127#u8)
          let i4 ← lift (UScalar.cast .U32 i3)
          let number1 ← lift (i2 ||| i4)
          let count1 ← count + 1#usize
          let i5 ← i + 1#usize
          let i6 ← lift (b &&& 128#u8)
          if i6 = 0#u8
          then ok (done (core.result.Result.Ok (number1, i5)))
          else ok (cont (i5, number1, count1))
    else
      let i1 ← core.num.U32.MAX >>> 7#i32
      if number > i1
      then ok (done (core.result.Result.Err tag.TagError.TooLarge))
      else
        let i2 ← number <<< 7#i32
        let i3 ← lift (b &&& 127#u8)
        let i4 ← lift (UScalar.cast .U32 i3)
        let number1 ← lift (i2 ||| i4)
        let count1 ← count + 1#usize
        let i5 ← i + 1#usize
        let i6 ← lift (b &&& 128#u8)
        if i6 = 0#u8
        then ok (done (core.result.Result.Ok (number1, i5)))
        else ok (cont (i5, number1, count1))

/-- [der_tag_extract::tag::decode_tag]: loop 0:
    Source: 'src/../../../der-verified/src/tag.rs', lines 125:48-142:5
    Visibility: public -/
@[rust_loop]
def tag.decode_tag_loop
  (i : Std.Usize) (input : Slice Std.U8) (number : Std.U32) (count : Std.Usize)
  :
  Result (core.result.Result (Std.U32 × Std.Usize) tag.TagError)
  := do
  loop
    (fun (i1, number1, count1) => tag.decode_tag_loop.body input i1 number1
      count1)
    (i, number, count)

/-- [der_tag_extract::tag::decode_tag]:
    Source: 'src/../../../der-verified/src/tag.rs', lines 94:0-148:1
    Visibility: public -/
def tag.decode_tag
  (input : Slice Std.U8) :
  Result (core.result.Result (tag.Tag × Std.Usize) tag.TagError)
  := do
  let o ← core.slice.Slice.first input
  match o with
  | none => ok (core.result.Result.Err tag.TagError.Truncated)
  | some b =>
    let i ← b >>> 6#i32
    let class1 ←
      match i with
      | 0#uscalar => ok tag.Class.Universal
      | 1#uscalar => ok tag.Class.Application
      | 2#uscalar => ok tag.Class.ContextSpecific
      | _ => ok tag.Class.Private
    let i1 ← lift (b &&& 32#u8)
    let i2 ← lift (b &&& 31#u8)
    if i2 != 31#u8
    then
      let i3 ← lift (b &&& 31#u8)
      let i4 ← lift (UScalar.cast .U32 i3)
      ok (core.result.Result.Ok
        ({ «class» := class1, constructed := (i1 != 0#u8), number := i4 },
        1#usize))
    else
      let state ← tag.decode_tag_loop 1#usize input 0#u32 0#usize
      let cf ← core.result.Result.Insts.CoreOpsTry.branch state
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let (number, i3) := val
        if number <= 30#u32
        then ok (core.result.Result.Err tag.TagError.NonMinimal)
        else
          ok (core.result.Result.Ok
            ({ «class» := class1, constructed := (i1 != 0#u8), number }, i3))
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
          (tag.Tag × Std.Usize) (core.convert.FromSame tag.TagError) residual

end der_tag_extract
